
stages:
  - test
  - build

before_script:
  - dotnet --version

test:all:
  image: "mcr.microsoft.com/dotnet/core/sdk:3.1"
  stage: test
  script:
   - dotnet test HellowTest/HellowTest.csproj

build:hellow:
  image: "mcr.microsoft.com/dotnet/core/sdk:3.1"
  stage: build
  script:
   - dotnet publish -c Release -o publish hellow/hellow.csproj
  tags:
   - docker
  only:
    refs:
     - develop
  artifacts:
    paths:
      - publish/

build:hellowapi:
  image: "mcr.microsoft.com/dotnet/core/sdk:3.1"
  stage: build
  script:
   - dotnet publish -c Release -o publish hellowapi/hellowapi.csproj
  tags:
   - docker
  only:
    refs:
     - develop
  artifacts:
    paths:
      - publish/
