
stages:
  - build

build:hellow:
  image: "mcr.microsoft.com/dotnet/core/sdk:3.1"
  stage: build
  script:
   - dotnet --version
   - dotnet build hellow
  tags:
   - docker
  only:
    refs:
     - develop
