image: "mcr.microsoft.com/dotnet/core/sdk:3.1"

stages:
  - test
  - build
  - release

before_script:
  - echo "=== Loading our self-signed CA certificate into Trust Store ==="
  - cat "$CA_SS_CERT" > /usr/local/share/ca-certificates/our.crt && update-ca-certificates
  - echo "==============================================================="
  - dotnet --version

test:all:
  stage: test
  script:
    - dotnet test HellowTest/HellowTest.csproj

build:hellow:
  stage: build
  script:
    - dotnet publish -c Release -o publish hellow/hellow.csproj
  tags:
    - docker
  only:
    refs:
      - develop
  artifacts:
    paths:
      - publish/

build:hellowapi:
  stage: build
  script:
    - dotnet publish -c Release -o publish hellowapi/hellowapi.csproj
  tags:
    - docker
  only:
    refs:
      - develop
  artifacts:
    paths:
      - publish/

package:create:
  stage: release
  script:
    - dotnet pack -c Release -o packages myCommon/myCommon.csproj
    - dotnet pack -c Release -o packages hellow/hellow.csproj
  tags:
    - docker
  only:
    refs:
      - develop
  artifacts:
    paths:
      - packages/

package:publish:
  variables:
    NEXUS_NUGET_REPO: https://nexus.ashby.ch/repository/nuget-hosted/
  stage: release
  script:
    - dotnet nuget push packages/*.nupkg --api-key $NUGET_API_KEY --source $NEXUS_NUGET_REPO
  tags:
    - docker
  only:
    refs:
      - develop
  needs:
    - package:create
